spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: MySQLroot11*
    url: jdbc:mysql://localhost:3306/products
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
